import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className=" bg-gray-800 p-6">
          <h1 className=" font-bold text-2xl">Convolutional Neural Networks</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
